// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Yt4Ab-LUBJfkHxynDuLQUBKrlJgOwPE',
    appId: '1:820343991980:web:c082aca1622900a293b909',
    messagingSenderId: '820343991980',
    projectId: 'cybernated-attendance-sy-8a74c',
    authDomain: 'cybernated-attendance-sy-8a74c.firebaseapp.com',
    storageBucket: 'cybernated-attendance-sy-8a74c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzxNZRtdZOzpA-o0Pw7nlnb4gs_7oADgM',
    appId: '1:820343991980:android:5f4cba64988d0afd93b909',
    messagingSenderId: '820343991980',
    projectId: 'cybernated-attendance-sy-8a74c',
    storageBucket: 'cybernated-attendance-sy-8a74c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA00BjYnu6vQwNagS7iZZIvJnEKixfMZ80',
    appId: '1:820343991980:ios:dfb60662c83c15fb93b909',
    messagingSenderId: '820343991980',
    projectId: 'cybernated-attendance-sy-8a74c',
    storageBucket: 'cybernated-attendance-sy-8a74c.appspot.com',
    iosClientId: '820343991980-jsdsj1bfid4q4ol9aodn4f39pmp52muh.apps.googleusercontent.com',
    iosBundleId: 'com.example.cybernatedAttendenceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA00BjYnu6vQwNagS7iZZIvJnEKixfMZ80',
    appId: '1:820343991980:ios:dfb60662c83c15fb93b909',
    messagingSenderId: '820343991980',
    projectId: 'cybernated-attendance-sy-8a74c',
    storageBucket: 'cybernated-attendance-sy-8a74c.appspot.com',
    iosClientId: '820343991980-jsdsj1bfid4q4ol9aodn4f39pmp52muh.apps.googleusercontent.com',
    iosBundleId: 'com.example.cybernatedAttendenceSystem',
  );
}
